apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_CLIENT_ID: <your GITHUB_CLIENT_ID>
  GITHUB_CLIENT_SECRET: <your GITHUB_CLIENT_SECRET>
  AZURE_CLIENT_ID: <your AZURE_CLIENT_ID>
  AZURE_CLIENT_SECRET: <your AZURE_CLIENT_SECRET>
  AZURE_TENANT_ID: <your AZURE_TENANT_ID>
