apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  APP_BASEURL: <Your APP_BASEURL>
  BACKEND_BASEURL: <Your BACKEND_BASEURL>
  BACKEND_PORT: <Your BACKEND_PORT>
