apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  APP_BASEURL: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  BACKEND_BASEURL: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  BACKEND_PORT: NzAwNw==