name: Deploy a MSA React App

on:
  workflow_dispatch:
    inputs:
      appName: 
        description: 'Application Name'
        required: true
      backendName:
        description: 'Backend Name'
        required: true
      backendImageName:
        description: 'Backend Container Image Name'
        required: true
      frontendName:
        description: 'Frontend Name'
        required: true
      frontendImageName:
        description: 'Frontend Container Image Name'
        required: true
      repoURLforArgo: 
        description: 'The URL of the repository for Argo CD to deploy the MSA App'
        required: true
      repo:
        description: 'Repo name'
        required: true
      owner:
        description: 'owner of repo'
        required: true
jobs:
  deploy-msa-react:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Install NGINX
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Checkout external repository for Dockerfile
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }}  # External repo with Dockerfile
        path: ${{ github.event.inputs.repo }} # Where to check out the external repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.repoURLforArgo }}/src/backend  # Path to Dockerfile in external repo
        file: ./${{ github.event.inputs.repoURLforArgo }}/src/backend/Dockerfile  # Explicit path to Dockerfile
        push: true  # Push to Docker Hub
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.backendImageName }}:latest  # Change your-image-name
    
    - name: Build and Push FrontEnd Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.repoURLforArgo }}/src/frontend  # Path to Dockerfile in external repo
        file: ./${{ github.event.inputs.repoURLforArgo }}/src/frontend/Dockerfile  # Explicit path to Dockerfile
        push: true  # Push to Docker Hub
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.frontendImageName }}:latest  # Change your-image-name
 
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD 
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --insecure --grpc-web 

    - name: Register Repository in Argo CD
      run: |
          argocd repo add ${{ github.event.inputs.repoURLforArgo }} --username hoanglecao --password ${{ secrets.MYGITHUB_TOKEN }}

    - name: Deploy MSA React Application
      run: |
        argocd app create ${{ github.event.inputs.appName }} \
          --repo ${{ github.event.inputs.repoURLforArgo }} \
          --path deployment \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace ${{ github.event.inputs.appName }} \
          --project default \
          --sync-policy automated \
          --sync-option CreateNamespace=true \
          --upsert \
          --grpc-web
