name: Deploy a MSA React App On Cluster

on:
  workflow_dispatch:
    inputs:
      backendName:
        description: 'Backend Name'
        required: true
      backendImageName:
        description: 'Backend Container Image Name'
        required: true
      frontendName:
        description: 'Frontend Name'
        required: true
      frontendImageName:
        description: 'Frontend Container Image Name'
        required: true
      repoURLforArgo: 
        description: 'The URL of the repository for Argo CD to deploy the MSA App'
        required: true
      repo:
        description: 'Repo name'
        required: true
      owner:
        description: 'owner of repo'
        required: true
      host:
        description: 'github.com or azure.dev.com'
        required: true
      organization:
        description: 'Azure DevOps organization'
        required: true
      project:
        description: 'Azure DevOps project'
        required: true
jobs:
  deploy-msa-react:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Install NGINX
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Checkout external repository for Dockerfile
      id: checkout_dockerfile_repo
      run: |
        if [[ ${{ github.event.inputs.host }} == "github.com" ]]; then
          echo "Checking out GitHub repository for Dockerfile..."
          echo "::set-output name=repo_url::${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }}"
          echo "::set-output name=token::${{ secrets.MYGITHUB_TOKEN }}"
        elif [[ ${{ github.event.inputs.host }} == "dev.azure.com" ]]; then
          echo "Checking out Azure DevOps repository for Dockerfile..."
          echo "::set-output name=repo_url::${{ github.event.inputs.organization }}/${{ github.event.inputs.project }}/${{ github.event.inputs.repo }}"
          echo "::set-output name=token::${{ secrets.MYAZURE_TOKEN }}"
        else
          echo "Unsupported repository host: ${{ github.event.inputs.host }} "
          exit 1
        fi

    - name: Checkout external repository for Dockerfile
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.checkout_dockerfile_repo.outputs.repo_url }}
        path: ${{ github.event.inputs.repo }} 
        token: ${{ steps.checkout_dockerfile_repo.outputs.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.repo }}/src/backend  # Path to Dockerfile in external repo
        file: ./${{ github.event.inputs.repo }}/src/backend/Dockerfile  # Explicit path to Dockerfile
        push: true  # Push to Docker Hub
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.backendImageName }}:latest  # Change your-image-name
    
    - name: Build and Push FrontEnd Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.repo }}/src/frontend  # Path to Dockerfile in external repo
        file: ./${{ github.event.inputs.repo }}/src/frontend/Dockerfile  # Explicit path to Dockerfile
        push: true  # Push to Docker Hub
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.frontendImageName }}:latest  # Change your-image-name

    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD 
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --insecure --grpc-web 

    - name: Register Repository in Argo CD
      run: |
          if [[ ${{ github.event.inputs.host }} == "github.com" ]]; then
            echo "Registering GitHub repository in ArgoCD..."
            argocd repo add ${{ github.event.inputs.repoURLforArgo }} --username hoanglecao --password ${{ secrets.MYGITHUB_TOKEN }}
          
          elif [[ ${{ github.event.inputs.host }} == "dev.azure.com" ]]; then
            echo "Registering Azure DevOps repository in ArgoCD..."
            argocd repo add ${{ github.event.inputs.repoURLforArgo }} --username lecao --password ${{ secrets.MYAZURE_TOKEN }}
          
          else
            echo "Unsupported repository host: $REPO_HOST"
            exit 1
          fi

    - name: Deploy MSA React Application
      run: |
        argocd app create todo-app \
          --repo ${{ github.event.inputs.repoURLforArgo }} \
          --path deployment \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace todo-app \
          --project default \
          --sync-policy automated \
          --sync-option CreateNamespace=true \
          --upsert \
          --grpc-web

    - name: Wait for todo-app to become synced
      run: |
        # Initialize time
        TIMEOUT=660
        INTERVAL=60
        ELAPSED=0

        # Loop until the app becomes healthy and synced or we hit the timeout
        while [[ $ELAPSED -lt $TIMEOUT ]]; do
          # Get the health status and sync status of the application
          APP_STATUS=$(argocd app get todo-app --output json)
          HEALTH_STATUS=$(echo "$APP_STATUS" | jq -r '.status.health.status')
          SYNC_STATUS=$(echo "$APP_STATUS" | jq -r '.status.sync.status')
          echo "Application health status: $HEALTH_STATUS"
          echo "Application sync status: $SYNC_STATUS"

          # If the app is both healthy and synced, break out of the loop
          if [[ "$HEALTH_STATUS" == "Healthy" && "$SYNC_STATUS" == "Synced" ]]; then
            echo "todo-app is healthy and synced. Proceeding..."
            break
          fi

          # Wait for the interval duration before checking again
          echo "Waiting for todo-app to become healthy and synced..."
          sleep $INTERVAL

          # Increment the elapsed time
          ELAPSED=$((ELAPSED + INTERVAL))
          done

          # If the app is still not healthy or synced after the timeout, exit with an error
          if [[ "$HEALTH_STATUS" != "Healthy" || "$SYNC_STATUS" != "Synced" ]]; then
            echo "todo-app did not become healthy and synced within $TIMEOUT seconds. Exiting..."
            exit 1
          fi