name: Manage GKE Cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
      region:
        description: 'Region'
        required: true
      machineType:
        description: 'Machine Type'
        required: true
      nodeCount:
        description: 'Node Count'
        required: true
      repoURLforArgo: 
        description: 'The URL of the repository for Argo CD to deploy GKE'
        required: true

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD 
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --insecure --grpc-web 

    - name: Register Repository in Argo CD
      run: argocd repo add ${{ github.event.inputs.repoURLforArgo }} --username hoanglecao --password ${{ secrets.MYGITHUB_TOKEN }}

    - name: Deploy GKE Cluster with Argo CD
      run: |
          argocd app create gcp-infrastructure-${{ github.event.inputs.clusterName }} \
            --repo ${{ github.event.inputs.repoURLforArgo }} \
            --path infrastructure \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace infrastructure \
            --project default \
            --sync-policy automated \
            --sync-option CreateNamespace=true  \
            --sync-retry-limit 5 \
            --upsert \
            --grpc-web