name: Manage EKS Cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
      region:
        description: 'Region'
        required: true     
      repoURLforArgo: 
        description: 'The URL of the repository for Argo CD to deploy GKE'
        required: true
      host:
        description: 'github.com or azure.dev.com'
        required: true
      customKyvernoPolicies:
        description: 'Custom Policy Repository Location'
        required: false
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Install kubectl
      run: |
        if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
          sudo apt-get update
          sudo apt-get install -y kubectl
        else
          echo "No custom Kyverno Policies provided."
        fi
    
    # Install Helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

            
    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD 
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --insecure --grpc-web 


    - name: Configure kubectl for EKS
      run: |
          aws eks --region "${{ github.event.inputs.region }}" update-kubeconfig --name "${{ github.event.inputs.clusterName }}"

    - name: Install Kyverno in the Kubernetes cluster
      run: |
          if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
            helm repo add kyverno https://kyverno.github.io/kyverno/
            helm repo update
            helm install kyverno kyverno/kyverno -n kyverno --create-namespace
          fi

    - name: Clone Kyverno Policy Repository
      run: |
        if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
          rm -rf kyverno || true  # Clean previous clone if it exists
          git clone https://github.com/nashtech-garage/kyverno.git
        fi

    - name: Apply Kyverno Policies
      run: |
        if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
          if [ -d "kyverno/policies/pod-security/" ]; then
            kubectl apply -f kyverno/policies/pod-security/
          else
            echo "Policy directory not found."
            exit 1
          fi
        fi
